# Generated by Django 2.0.4 on 2018-05-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0002_auto_20180518_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='description',
        ),
    ]
