# Generated by Django 2.0.4 on 2018-05-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0003_remove_crop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
