# Generated by Django 2.0.4 on 2018-05-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0004_crop_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='category',
        ),
    ]
