# Generated by Django 2.0.4 on 2018-05-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0005_auto_20180518_0948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
