# Generated by Django 2.0.4 on 2018-05-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0007_auto_20180518_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizer',
            name='voice_label',
        ),
        migrations.RemoveField(
            model_name='tutorials',
            name='voice_label',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='fertilizers',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='tutorial',
        ),
        migrations.DeleteModel(
            name='Fertilizer',
        ),
        migrations.DeleteModel(
            name='Tutorials',
        ),
    ]
