# Generated by Django 2.0.4 on 2018-05-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0009_auto_20180521_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tutorials',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
