# Generated by Django 2.0.4 on 2018-05-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0010_auto_20180521_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='category',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='fertilizers',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='tutorial',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='voice_label',
        ),
        migrations.RemoveField(
            model_name='fertilizer',
            name='voice_label',
        ),
        migrations.RemoveField(
            model_name='tutorials',
            name='voice_label',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='Fertilizer',
        ),
        migrations.DeleteModel(
            name='Tutorials',
        ),
    ]
