# Generated by Django 2.0.4 on 2018-05-21 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0011_auto_20180521_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('img_url', models.URLField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_development.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('image_url', models.URLField(null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('voice_label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_development.VoiceLabel')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('voice_label', models.ManyToManyField(blank=True, to='service_development.VoiceLabel')),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='fertilizers',
            field=models.ManyToManyField(to='service_development.Fertilizer'),
        ),
        migrations.AddField(
            model_name='crop',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_development.Tutorials'),
        ),
        migrations.AddField(
            model_name='crop',
            name='voice_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_development.VoiceLabel'),
        ),
    ]
