# Generated by Django 2.0.4 on 2018-05-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0012_auto_20180521_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tutorials',
            name='description',
        ),
    ]
