# Generated by Django 2.0.4 on 2018-05-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0013_auto_20180521_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizer',
            name='voice_label',
        ),
    ]
