# Generated by Django 2.0.4 on 2018-05-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0014_remove_fertilizer_voice_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='voice_label',
        ),
    ]
